# Generated by Django 5.2.1 on 2025-05-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InternApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('arrears', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('clg_mailid', models.EmailField(max_length=254)),
                ('course_duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ips_intern.courseduration')),
            ],
        ),
    ]
