# Generated by Django 5.2.3 on 2025-06-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0003_taskreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='arrears',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
