# Generated by Django 5.2.3 on 2025-06-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0005_internapplication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='is_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
