# Generated by Django 5.2.3 on 2025-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0006_internapplication_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
