# Generated by Django 5.2.3 on 2025-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0007_alter_internapplication_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
