# Generated by Django 5.2.3 on 2025-06-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0008_internapplication_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
