# Generated by Django 5.2.3 on 2025-06-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0009_internapplication_is_certified'),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
