# Generated by Django 5.2.3 on 2025-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0010_internapplication_certificate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internapplication',
            name='certificate_file',
        ),
        migrations.AddField(
            model_name='internapplication',
            name='just_approved',
            field=models.BooleanField(default=False),
        ),
    ]
