# Generated by Django 5.2.3 on 2025-06-30 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ips_intern', '0012_internapplication_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
